#!/bin/bash
echo "Updating system and installing Tesseract OCR..."
sudo apt-get update -y
sudo apt-get install -y tesseract-ocr libtesseract-dev tesseract-ocr-eng
echo "Tesseract installation complete!"
