#!/bin/bash
echo "Installing Tesseract OCR..."
sudo apt-get update -y
sudo apt-get install -y tesseract-ocr libtesseract-dev
sudo apt-get install -y tesseract-ocr-eng
echo "Tesseract installation complete!"
